name: 'CC0 3DS'
description: 'Free 3D Models & Public Domain 3D Game Assets'
author: 'Mohamad Rido'
email: 'cc03ds@mail.ru'
permalink: /:title
plugin:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
paginate: 15
